security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 10
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            stateless: true # Make the firewall stateless for JWT authentication
            anonymous: false  
            provider: users_in_memory
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator  

            logout:
                delete_cookies:
                    JWT: null
                path: /logout
                target: /login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/volunteer, roles: ROLE_VOLUNTEER }
        # - { path: ^/donor, roles: ROLE_DONOR }
        # - { path: ^/admin, roles: ROLE_ADMIN }
