security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
            cost: 10
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
            stateless: true # Make the firewall stateless for JWT authentication
            anonymous: false  

            # Add the JWT authenticator and your custom authenticator to the list
            guard:
                authenticators:
                    - App\Security\JwtAuthenticator # Your custom authenticator should be the entry point
                    - lexik_jwt_authentication.jwt_token_authenticator

            # Set your custom authenticator as the entry point
            entry_point: App\Security\JwtAuthenticator

            logout:
                delete_cookies:
                    JWT: null
                path: /logout
                target: /login

        login:
            pattern: ^/login
            stateless: false
            json_login:
                check_path: /login/process
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/volunteer, roles: ROLE_VOLUNTEER }
        # - { path: ^/donor, roles: ROLE_DONOR }
        # - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
